# Generated by Django 4.2.7 on 2023-12-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Categori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categori_name', models.CharField(max_length=100)),
                ('categori_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('categori_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_categori')),
            ],
        ),
    ]
